# Generated by Django 5.2.13 on 2026-04-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_skills', models.TextField(help_text='Comma-separated required skills')),
                ('education_requirement', models.CharField(blank=True, max_length=255)),
                ('experience_requirement', models.DecimalField(decimal_places=1, default=0.0, help_text='Minimum years of experience', max_digits=4)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DRAFT', 'Draft')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='accounts.recruiterprofile')),
            ],
        ),
    ]
